# -*- coding: utf-8 -*-
"""VGG16_From_Scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csuQ5lGwx1Vq1LxekAJybKRa34XDjpR_
"""

!mkdir -p ~/.kaggle

!mv kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d jtiptj/chest-xray-pneumoniacovid19tuberculosis

!unzip /content/chest-xray-pneumoniacovid19tuberculosis.zip -d /content/

import tensorflow as tf
from tensorflow.keras import layers,models
from tensorflow.keras.layers import Rescaling

#for Reproducibility
import numpy as np
import random
import os
seed=123
random.seed(seed)
np.random.seed(seed)
tf.random.set_seed(seed)

#Directoried containing the dataset

train_dir="/content/train/"
test_dir="/content/test/"
val_dir="/content/val/"

#Hyper Parameters
img_width,img_height=224,224
batch_size=32
epochs=20
num_classes=4 # Update based on your dataset

#Load the datasets without validation split
train_dataset=tf.keras.preprocessing.image_dataset_from_directory(
    train_dir,
    image_size=(img_width,img_height),
    batch_size=batch_size,
    shuffle=True
)

validation_dataset=tf.keras.preprocessing.image_dataset_from_directory(
    val_dir,
    image_size=(img_width,img_height),
    batch_size=batch_size,
)

test_dataset=tf.keras.preprocessing.image_dataset_from_directory(
    test_dir,
    image_size=(img_width,img_height),
    batch_size=batch_size,
)

#Data Augmentation

data_augmentation=tf.keras.Sequential([
    layers.RandomFlip("horizontal_and_vertical"),
    layers.RandomRotation(0.2),
    layers.RandomZoom(0.2),
])

#Apply data augmentation onlt to the training data
train_dataset=train_dataset.map(lambda x,y:(data_augmentation(x,training=True),y))

#prefetch the datasets for better perfromanec
AUTOTUNE=tf.data.AUTOTUNE
train_dataset=train_dataset.prefetch(buffer_size=AUTOTUNE)
validation_dataset=validation_dataset.prefetch(buffer_size=AUTOTUNE)

"""- Machine Learning Pipeline Steps

    - Data Preparation
        
        Get the dataset: Acquire the dataset (e.g., from files, APIs, or databases).

        Normalise the dataset: Scale features (e.g., MinMax, StandardScaler).

        Use validation split: Reserve a portion of data for validation (e.g., train_test_split).

    - Data Pipeline Optimization

        Initialise generators: Set up data generators (e.g., tf.data.Dataset or ImageDataGenerator).

        Data Augmentation: Apply transformations (e.g., rotation, flipping) to improve generalization.

        Autotune and prefetch: Optimize I/O performance (e.g., tf.data.AUTOTUNE).

    - Model Development

        Model Building: Define architecture (e.g., CNN, LSTM).

        Model summary: Print layer details (e.g., model.summary()).

    - Training & Evaluation

        Model compile: Configure optimizer, loss, metrics (e.g., model.compile()).

        Model training: Fit the model (e.g., model.fit()).

        Model evaluation: Assess performance on train/test/validation sets (e.g., model.evaluate()).

    - Post-Training

        Performance plots and metrics: Visualize accuracy/loss curves, compute metrics (e.g., ROC, F1).

        Model save: Export the model (e.g., model.save() or HDF5 format).
"""

from tensorflow.keras import layers, models
from tensorflow.keras.layers import Rescaling

def build_vgg16(input_shape=(224,224,3), num_classes=4):
    model = models.Sequential()

    # Input Layer with Normalization
    model.add(layers.Input(shape=input_shape))
    model.add(Rescaling(1./255))  # Normalize pixel values to [0,1]

    # Block 1
    model.add(layers.Conv2D(64, (3,3), padding="same", activation="relu"))
    model.add(layers.Conv2D(64, (3,3), padding="same", activation="relu"))
    model.add(layers.MaxPooling2D((2,2), strides=(2,2)))  # Fixed syntax

    # Block 2
    model.add(layers.Conv2D(128, (3,3), padding="same", activation="relu"))
    model.add(layers.Conv2D(128, (3,3), padding="same", activation="relu"))
    model.add(layers.MaxPooling2D((2,2), strides=(2,2)))

    # Block 3
    model.add(layers.Conv2D(256, (3,3), padding="same", activation="relu"))
    model.add(layers.Conv2D(256, (3,3), padding="same", activation="relu"))
    model.add(layers.Conv2D(256, (3,3), padding="same", activation="relu"))
    model.add(layers.MaxPooling2D((2,2), strides=(2,2)))

    # Block 4
    model.add(layers.Conv2D(512, (3,3), padding="same", activation="relu"))
    model.add(layers.Conv2D(512, (3,3), padding="same", activation="relu"))
    model.add(layers.Conv2D(512, (3,3), padding="same", activation="relu"))
    model.add(layers.MaxPooling2D((2,2), strides=(2,2)))

    # Block 5
    model.add(layers.Conv2D(512, (3,3), padding="same", activation="relu"))
    model.add(layers.Conv2D(512, (3,3), padding="same", activation="relu"))
    model.add(layers.Conv2D(512, (3,3), padding="same", activation="relu"))
    model.add(layers.MaxPooling2D((2,2), strides=(2,2)))

    # Fully Connected Layers
    model.add(layers.Flatten())
    model.add(layers.Dense(4096, activation="relu"))
    model.add(layers.Dropout(0.5))
    model.add(layers.Dense(4096, activation="relu"))
    model.add(layers.Dropout(0.5))
    model.add(layers.Dense(num_classes, activation="softmax"))

    return model

model=build_vgg16(num_classes=num_classes)
model.summary()

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
#Use 'categorixal_crossentropy' if labels are one-hot encoded

history=model.fit(
    train_dataset,
    epochs=epochs,
    validation_data=validation_dataset
)

#VGG16 is not trained enough, or 20 epochs is not good enough,

#The thing is model is not trained well good enough , or vgg16 is not good for our task
#VGG16 is properly build on ImageNet Dataset , which doesn;t have any properties like x-ray dataset

#So at this scenario our custom build vgg16 doesn't work well good enough

acc=history.history['accuracy']
val_acc=history.history['val_accuracy']
loss=history.history['loss']
val_loss=history.history['val_loss']

epochs_range=range(len(epochs))

plt.figure(figsize=(20,5))
plt.subplot(1,2,1)
plt.plot(epochs_range,acc,label='Training Accuracy')
plt.plot(epochs_range,val_acc,label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1,2,2)
plt.plot(epochs_range,loss,label='Training Loss')
plt.plot(epochs_range,val_loss,label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')

plt.show()

#Isse Humlog dekh lenge ki Training me 1 epoch ke baad model is not learning anything so hume new model hi banana padega and there is very huge diffefence on margin b/w training and validation

#Maybe we have some images from test dataset to validation dataset to increase the sizeof validation datatset

#You need to find out ki acha aha pe ilega

test_loss,test_accuracy=model.evaluate(test_dataset)
print(f"Test Accuracy: {test_accuracy*100:.2f}%")

#Train set predictions
y_train_pred=model.predict(train_dataset)
y_train_pred=np.argmax(y_train_pred,axis=1)
y_train=np.concatenate([y for x,y in train_dataset],axis=0)

#Validation set predictions
y_val_pred=model.predict(validation_dataset)
y_val_pred=np.argmax(y_val_pred,axis=1)
y_val=np.concatenate([y for x,y in validation_dataset],axis=0)

#Test set predictions
y_test_pred=model.predict(test_dataset)
y_test_pred=np.argmax(y_test_pred,axis=1)
y_test=np.concatenate([y for x,y in test_dataset],axis=0)

from functools import cmp_to_key
from sklearn.metrics import confusion_matrix

#Confusion matrices
cm_train = confusion_matrix(y_train, y_train_pred)
cm_val = confusion_matrix(y_val, y_val_pred)
cm_test = confusion_matrix(y_test, y_test_pred)

#Set up the figure

fig,axes=plt.subplots(1,3,figsize=(15,5))

#Train Confusion Matix
sns.heatmap(cm_train,annot=True,fmt='d',cmap='Blues',ax=axes[0])
axes[0].set_title('Train Confusion Matrix')
axes[0].set_xlabel('Predicted Labels')
axes[0].set_ylabel('True Labels')

#Validation Confusion Matrix
sns.heatmap(cm_train,annot=True,fmt='d',cmap='Blues',ax=axes[1])
axes[1].set_title('Validation Confusion Matrix')
axes[1].set_xlabel('Predicted Labels')
axes[1].set_ylabel('True Labels')

#Test Confusion Matrix
sns.heatmap(cm_train,annot=True,fmt='d',cmap='Blues',ax=axes[2])
axes[2].set_title('Test Confusion Matrix')
axes[2].set_xlabel('Predicted Labels')
axes[2].set_ylabel('True Labels')

#Adjust Layout
plt.tight_layout()
plt.show()

"""## Very Bad Results

## Transfter Learning
"""

import tensorflow as tf
from tensorflow.keras.applications import VGG16
from tensorflow.keras import layers,models
from tensorflow.keras.preprocessing import image_dataset_from_directory
from tensorflow.keras.layers import Input

# Load VGG16 with pre-trained weights, excluding the top (fully connected layers)
base_model = VGG16(weights='imagenet', include_top=False, input_tensor=Input(shape=(img_width, img_height, 3)))

# Print model summary
base_model.summary()

#If you keep the include_top=False , then they will not add the 3 fully connected layers to the architechture

#Freeze the layers in the base model
for layer in base_model.layers:
    layer.trainable=False

#Build the model
model=models.Sequential([
    base_model,
    layers.Flatten(),
    layers.Dense(512,activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(num_classes,activation='softmax')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

"""# Transfer learning iwth fixed Weights in convolutions and training model on FC Layers"""

history=model.fit(
    train_dataset,
    validation_data=validation_dataset,
    epochs=epochs
)

import matplotlib.pyplot as plt

acc=history.history['accuracy']
val_acc=history.history['val_accuracy']
loss=history.history['loss']
val_loss=history.history['val_loss']

epochs_range=range(epochs)

plt.figure(figsize=(20,5))
plt.subplot(1,2,1)
plt.plot(epochs_range,acc,label='Training Accuracy')
plt.plot(epochs_range,val_acc,label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1,2,2)
plt.plot(epochs_range,loss,label='Training Loss')
plt.plot(epochs_range,val_loss,label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training an dValidation Loss')
plt.show()

test_loss,test_accuracy=model.evaluate(test_dataset)
print(f"Test Accuracy: {test_accuracy*100:.2f}%")

#Train set predictions
y_train_true=np.concatenate([y for x,y in train_dataset],axis=0)
y_train_pred=model.predict(train_dataset)
y_train_pred=np.argmax(y_train_pred,axis=1)

#Validation set predictions
y_val_true=np.concatenate([y for x,y in validation_dataset],axis=0)
y_val_pred=model.predict(validation_dataset)
y_val_pred=np.argmax(y_val_pred,axis=1)

#Test set predictions
y_test_true=np.concatenate([y for x,y in test_dataset],axis=0)
y_test_pred=model.predict(test_dataset)
y_test_pred=np.argmax(y_test_pred,axis=1)

from sklearn.metrics import confusion_matrix

#Confusion Matrix
cm_train=confusion_matrix(y_train_true,y_train_pred)
cm_val=confusion_matrix(y_val_true,y_val_pred)
cm_test=confusion_matrix(y_test_true,y_test_pred)

import seaborn as sns

fig,axes=plt.subplots(1,3,figsize=(15,5))

#Train Confusion Matrix
sns.heatmap(cm_train,annot=True,fmt='d',cmap='Blues',ax=axes[0])
axes[0].set_title('Train Confusion Matrix')
axes[0].set_xlabel('Predicted Labels')
axes[0].set_ylabel('True Labels')

#Validation Confusion Matrix
sns.heatmap(cm_val,annot=True,fmt='d',cmap='Blues',ax=axes[1])
axes[1].set_title('Validation Confusion Matrix')
axes[1].set_xlabel('Predicted Labels')
axes[1].set_ylabel('True Labels')

#Test Confusion Matrix
sns.heatmap(cm_test,annot=True,fmt='d',cmap='Blues',ax=axes[2])
axes[2].set_title('Test Confusion Matrix')
axes[2].set_xlabel('Predicted Labels')
axes[2].set_ylabel('True Labels')

#Adjust layout
plt.tight_layout()
plt.show()

"""## Even More Finetuning"""

#Load VGG16 with pre-trained ImageNet weights , excluding the top(fully connected layers)
base_model=VGG16(weights='imagenet',include_top=False,input_tensor=Input(shape=(img_width,img_height,3)))

#Freeze the layers in the base model
for layer in base_model.layers[:15]: #Freeze first 15 layers , adjsut as Needed
    layer.trainable=False

#unfreeze the Remaining Layers
for layer in base_model.layers[15:]:
    layer.trainable=True

base_model.summary()

#Build the model
model=models.Sequential([
    base_model,
    layers.Flatten(),
    layers.Dense(512,activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(num_classes,activation='softmax')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history=model.fit(
    train_dataset,
    validation_data=validation_dataset,
    epochs=epochs
)

#Load VGG16 with pre-trained ImageNet weights, excluding the top(fully Connected) Layers
base_model=VGG16(weights='imagenet',
                 include_top=False,
                 input_tensor=Input(shape=(img_width,img_height,3)))

#Load VGG16 with pre-trained ImageNet weights , excluding the Top(follu Connected Layers)
base_model2=VGG16(weights='imagenet',
                  include_top=True,
                  input_tensor=Input(shape=(img_width,img_height,3)))

